- .gitignore
- client/webpack/dev.config.js
- package-lock.json
- package.json
- server/app.js
> added dotenv and historyApiFallback: true

- .gitignore
- server/db.js
> Loading the dotenv in the db

- client/src/App.js
- client/src/components/StudentCard.js
- client/src/components/StudentProfile.js
- client/src/components/StudentsGrid.js
- client/src/components/studentsGrid.css
- client/src/db/students.json
- package-lock.json
- package.json
> Created Route -Link to StudentCard and Profile .

- client/src/App.js
- client/src/components/StudentProfile.js
- client/src/components/studentsGrid.css
- client/src/db/students.json
> Added a student profile component

- client/src/components/FeedbackForm.js
- client/src/components/StudentProfile.js
- client/src/components/feedbackForm.css
- client/src/components/studentsGrid.css
> feedback form added

- client/src/db/students.json
> Profile Pictures Replaced

- client/src/App.js
- client/src/components/StudentCard.js
- client/src/components/StudentProfile.js
- client/src/components/StudentsGrid.js
- server/api.js
- server/app.js
- server/db.js
> Fetching data from the database

- client/src/components/StudentProfile.js
- client/src/contexts/StudentsContext.js
> Amending the fetch url to be relative not absolute

- client/src/index.html
> Changed app title

- server/api.js
> Created POST endpoint

- package.json
> Fix for port being in use

- client/src/components/FeedbackForm.js
- client/src/components/StudentProfile.js
- client/src/contexts/StudentsContext.js
- server/api.js
- server/db.js
> Mentor Name input area, given feedback stored on DB

- client/src/components/AreasOfFocus.js
- client/src/components/Navbar.js
- client/src/components/StudentProfile.js
- client/src/components/areasOfFocus.css
- client/src/components/studentProfile.css
unfortunately, I can not remove the linting problems Mo :( maybe we can try together this evening ? 
> AreasOfFocus component extracted/ areasOfFocus form added

- client/src/components/StudentCard/index.js
- client/src/contexts/StudentsContext.js
- server/api.js
- server/app.js
- server/db.js
The following requests are created: 
GET
/students
/students/:id
PUT
/students/:id
(to add new feedback or an area of focus)
> Endpoints created 

- client/src/App.js
- client/src/components/StudentCard/index.js
- client/src/components/StudentProfile/index.js
> StudentGrid / Profile Connected DB / Fetch removed from StudentProfile

- client/src/components/AreasOfFocus/index.js
- client/src/components/FormAreasOfFocus/index.js
- client/src/components/StudentProfile/index.js
In this fix, I rendered the areas of focus from the database in their sections on the Frontend.
> Fixing areas of focus to appear in their sections

- client/src/App.js
- client/src/components/PreviousFeedback/index.js
- client/src/components/PreviousFeedback/styles.css
- client/src/components/StudentProfile/index.js
> Prev-Feedback Component(FE Only), EndPoint Change(StudentProfile), Add Props to AreaOfFocus

- .vscode/settings.json
- client/src/components/AreasOfFocus/index.js
- client/src/components/AreasOfFocus/styles.css
- client/src/components/FeedbackForm/styles.css
- client/src/components/FormAreasOfFocus/index.js
- client/src/components/StudentProfile/index.js
- client/src/components/StudentProfile/styles.css
css for the areaOfFocus added (not everything finished yet) - the section is phone responsive 
maxLength for the area form added
> css for areas of focus added

- client/src/components/FeedbackForm/index.js
- client/src/components/PreviousFeedback/index.js
> Tidying up components

- client/src/components/PreviousFeedback/index.js
> PreviousFeedback in reverse order, recent feedback is on top.

- client/src/components/AreasOfFocus/index.js
- client/src/components/AreasOfFocus/styles.css
- client/src/components/StudentProfile/index.js
- client/src/components/StudentProfile/styles.css
just design small changes added
> delete button added to the area of focus / mail and github icon added 

- client/src/components/AllFeedback/index.js
- client/src/components/FeedbackForm/index.js
- client/src/components/PreviousFeedback/index.js
- client/src/components/StudentProfile/index.js
- package-lock.json
- package.json
- server/api.js
> Delete button deletes given feedback on DataBase, updates PreviousFeedback component

- client/src/components/AreasOfFocus/index.js
- client/src/components/StudentProfile/index.js
- server/api.js
> deleting the area and adding the new

- client/src/components/AreasOfFocus/index.js
- client/src/components/AreasOfFocusForm/index.js
please see below the changes applied with Guy / no testing made - backend updates needed
> draft pr / areas of focus

- client/src/components/PreviousFeedback/index.js
- server/api.js
> Delete feedback endpoint / METHOD changes

- client/src/components/FeedbackForm/index.js
- client/src/components/PreviousFeedback/index.js
Added timestamps for feedback and feedback posted ..... time ago
Fixed feedback form not clearing issue
Added feedback form mandatory fields from the FE to prevent from posting empty feedback
> Added timestamp for feedback and fixed the form

- client/src/App.css
- client/src/components/AreasOfFocus/index.js
- client/src/components/AreasOfFocus/styles.css
- client/src/components/AreasOfFocusInput/index.js
- client/src/components/AreasOfFocusInput/styles.css
- client/src/components/StudentProfile/styles.css
radio buttons styled in the areas of focus form 
buttons in all areas improved 
phone version not completely ready yet
> Ola / radio buttons styled in the areas of focus form 

- client/src/components/AllFeedback/index.js
- client/src/components/EditFeedback/index.js
- client/src/components/EditFeedback/styles.css
- client/src/components/PreviousFeedback/index.js
- client/src/components/PreviousFeedback/styles.css
- client/src/components/StudentsGrid/index.js
- server/api.js
Created Edit Feedback functionality on the FE. CSS is being processed. Corresponding BE will be implemented later.
> Edit feedback Functionality and edited feedback arrives at DB for processing.

- client/src/App.js
- client/src/components/Navbar/index.js
- client/src/components/RegionsCard/index.js
- client/src/components/RegionsCard/styles.css
- client/src/components/RegionsGrid/grid.css
- client/src/components/RegionsGrid/index.js
- client/src/components/RegionsGrid/styles.css
- client/src/components/StudentCard/index.js
- client/src/components/StudentProfile/index.js
- client/src/components/StudentsGrid/index.js
- client/src/db/regions.json
Core components added for CYF regions
All paths amended 
Functionality for filtering students by "city"
> CYF regions cards added

- client/src/App.js
- client/src/components/AllFeedback/index.js
- client/src/components/AreasOfFocus/index.js
- client/src/components/AreasOfFocusForm/index.js
- client/src/components/AreasOfFocusForm/styles.css
- client/src/components/EditFeedback/index.js
- client/src/components/FeedbackForm/index.js
- client/src/components/FeedbackForm/styles.css
- client/src/components/PreviousFeedback/index.js
- client/src/components/RegionsCard/index.js
- client/src/components/RegionsGrid/index.js
- client/src/components/StudentCard/index.js
- client/src/components/StudentProfile/index.js
- client/src/components/StudentsGrid/index.js
Fixed linter issues (mainly React Proptype)
Fixed page refreshing after prompt of missing fields
Little tweaks in some HTML tags and class names
> Fixing linter issues

- client/src/App.js
- client/src/components/AllFeedback/index.js
- client/src/components/AreasOfFocus/index.js
- client/src/components/FeedbackForm/styles.css
- client/src/components/HomePage/index.js
- client/src/components/Login/index.js
- client/src/components/Login/styles.css
- client/src/components/Navbar/index.js
- client/src/components/Navbar/styles.css
- client/src/components/StudentProfile/index.js
- client/src/components/StudentsGrid/index.js
- client/src/hooks/useForm.js
Added routes for: 
* Home page 
* Log In 
* Register
Added a custom hook (useForm)
Added external links for CYF website and syllabus
Added the following Navbar elements: 
* CYF logo
* Syllabus link
* Regions link
* Register button 
* Log In button
Some styling to the Navbar in accordance with CYF website
> New routes, useForm hook, Navbar additional elements

- client/src/components/AreasOfFocus/index.js
- client/src/components/Pagination/index.js
- client/src/components/Pagination/styles.css
- client/src/components/StudentsGrid/index.js
I did not use react extension.
> Ola pagination

- client/src/components/PreviousFeedback/index.js
Fixed filtering of the feedback and added sort.
> Fixing filtersand Adding  sort to filters

- client/src/components/Pagination/index.js
- client/src/components/PreviousFeedback/index.js
> Debug filter/ change filter formula

- client/src/components/PreviousFeedback/index.js
- client/src/components/PreviousFeedback/styles.css
Feedback Counter and Filter Debug
> Feedback Counter and Filter Debug

- client/src/components/PreviousFeedback/index.js
> Sort the feedbacks by the given time

- client/src/components/FeedbackForm/styles.css
- client/src/components/FeedbackObject/index.js
- client/src/components/FeedbackObject/styles.css
- client/src/components/Pagination/index.js
- client/src/components/PreviousFeedback/index.js
- client/src/components/PreviousFeedback/styles.css
Further Styling and class name changes on FeedbackObject
> Arrange Style and ClassNames on FeedbackObject

- client/src/components/Footer/styles.css
- client/src/components/Navbar/index.js
- client/src/components/Navbar/styles.css
- client/src/components/RegionsCard/styles.css
- client/src/components/RegionsGrid/index.js
- client/src/components/RegionsGrid/styles.css
- client/src/components/StudentCard/index.js
- client/src/components/StudentProfile/styles.css
- client/src/components/StudentsGrid/styles.css
all looks good in the sizzy app, I will use for the presentation. any more changes needed happy to add.
> css responsiv added
